### PR TITLE
Fix tab selection post deletion

### LINKED ISSUE #692: Incorrect tab selection after tab deletion
## Deleting the currently selected tab, should always select another tab if that's possible.
The issue is that it is not always working.
The current solution is attempting to select the tab that was "historically" created before the one deleted.
This works in the following tabs scenario:
```
Tab 1 (created @ 09:00)
Tab 2 (created @ 10:00) - selected and now marked to be deleted
```
Correctly, Tab 1 is selected.

The same approach won't work here:
```
Tab 1 (created @ 09:00) - selected and now marked to be deleted
Tab 2 (created @ 10:00) 
```
There are no tabs "created before 09:00" therefore the result is:
Tab 1 is deleted, but nothing is selected.

## Solution
Do not rely on the timestamp of the tabs, they are already ordered by that anyways, instead select the Tab before, if there's such, or select the Tab after if there's such.

### PR DESCRIPTION
**Pull request by BPerlakiH**
Fixes #692

### CODE REVIEW

File: ViewModel/NavigationViewModel.swift [hunk 1]
```diff
@@ -20,6 +20,8 @@ class NavigationViewModel: ObservableObject {
         let tab = Tab(context: context)
         tab.created = Date()
         tab.lastOpened = Date()
```
Comment (BPerlakiH) [inline ViewModel/NavigationViewModel.swift:22]: We were using the same set of operations after creating a tab:
- obtaining an DB id for it
- saving it
so it makes sense to bring those under the same function.

**Comment by kelson42** [comment]
@BPerlakiH Please update changelog

**Comment by BPerlakiH** [comment]
CHANGELOG updated.
