### PR TITLE
Fix search crashing

### LINKED ISSUE #631: Crash by searching in Wikimed custom app
Almost systematically crash if i type « fl ».

### LINKED ISSUE #635: Wikimed crashes when searching on MacOS and iOS
**Application:** Wikimed 1023.12.2 (133)
**OS:** MacOS 12.7.1 (Monterey)

**Reproducing steps:**
- open Wikimed application
- type `a` in the search bar (or `bo`, or probably many other things, some things are ok but then it rapidely crashes)
- 💥

<details>
<summary>Crash report</summary>
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               wikimed [14000]
Path:                  /Applications/wikimed.app/Contents/MacOS/wikimed
Identifier:            org.kiwix.wikimed
Version:               1023.12.2 (133)
App Item ID:           1281693200
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-01-23 08:25:07.6736 +0100
OS Version:            macOS 12.7.1 (21G920)
Report Version:        12
Anonymous UUID:        

Sleep/Wake UUID:       EAE0649E-F1CE-46CE-8072-39A0E41B875B

Time Awake Since Boot: 1100000 seconds
Time Since Wake:       60294 seconds

System Integrity Protection: enabled

Crashed Thread:        8  Dispatch queue: NSOperationQueue 0x7faec3159290 (QOS: UNSPECIFIED)

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 4 Illegal instruction: 4
Terminating Process:   exc handler [14000]

Thread 0::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	    0x7ff81324596a mach_msg_trap + 10
1   libsystem_kernel.dylib        	    0x7ff813245cd8 mach_msg + 56
2   CoreFoundation                	    0x7ff81334929d __CFRunLoopServiceMachPort + 319
3   CoreFoundation                	    0x7ff813347928 __CFRunLoopRun + 1276
4   CoreFoundation                	    0x7ff813346d6c CFRunLoopRunSpecific + 562
5   HIToolbox                     	    0x7ff81bff45e6 RunCurrentEventLoopInMode + 292
6   HIToolbox                     	    0x7ff81bff434a ReceiveNextEventCommon + 594
7   HIToolbox                     	    0x7ff81bff40e5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
8   AppKit                        	    0x7ff815d81f6d _DPSNextEvent + 927
9   AppKit                        	    0x7ff815d8062a -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394
10  AppKit                        	    0x7ff815d72cd9 -[NSApplication run] + 586
11  AppKit                        	    0x7ff815d46c57 NSApplicationMain + 817
12  SwiftUI                       	    0x7ff91e89209c specialized runApp(_:) + 161
13  SwiftUI                       	    0x7ff91f2f4424 runApp<A>(_:) + 164
14  SwiftUI                       	    0x7ff91edecc5f static App.main() + 63
15  wikimed                       	       0x10469019e 0x104679000 + 94622
16  dyld                          	       0x11463452e start + 462

Thread 1:
0   libsystem_pthread.dylib       	    0x7ff81327df48 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	    0x7ff81327df48 start_wqthread + 0

Thread 3:: JavaScriptCore libpas scavenger
0   libsystem_kernel.dylib        	    0x7ff8132483da __psynch_cvwait + 10
1   libsystem_pthread.dylib       	    0x7ff813282a6f _pthread_cond_wait + 1249
2   JavaScriptCore                	    0x7ff82bcbef25 scavenger_thread_main + 1397
3   libsystem_pthread.dylib       	    0x7ff8132824e1 _pthread_start + 125
4   libsystem_pthread.dylib       	    0x7ff81327df6b thread_start + 15

Thread 4:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	    0x7ff81324596a mach_msg_trap + 10
1   libsystem_kernel.dylib        	    0x7ff813245cd8 mach_msg + 56
2   CoreFoundation                	    0x7ff81334929d __CFRunLoopServiceMachPort + 319
3   CoreFoundation                	    0x7ff813347928 __CFRunLoopRun + 1276
4   CoreFoundation                	    0x7ff813346d6c CFRunLoopRunSpecific + 562
5   AppKit                        	    0x7ff815eef98e _NSEventThread + 132
6   libsystem_pthread.dylib       	    0x7ff8132824e1 _pthread_start + 125
7   libsystem_pthread.dylib       	    0x7ff81327df6b thread_start + 15

Thread 5:: com.apple.coreanimation.render-server
0   libsystem_kernel.dylib        	    0x7ff81324596a mach_msg_trap + 10
1   libsystem_kernel.dylib        	    0x7ff813245cd8 mach_msg + 56
2   QuartzCore                    	    0x7ff81a43ca47 CA::Render::Server::server_thread(void*) + 534
3   QuartzCore                    	    0x7ff81a43c826 thread_fun(void*) + 25
4   libsystem_pthread.dylib       	    0x7ff8132824e1 _pthread_start + 125
5   libsystem_pthread.dylib       	    0x7ff81327df6b thread_start + 15

Thread 6:
0   libsystem_pthread.dylib       	    0x7ff81327df48 start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	    0x7ff81327df48 start_wqthread + 0

Thread 8 Crashed::  Dispatch queue: NSOperationQueue 0x7faec3159290 (QOS: UNSPECIFIED)
0   wikimed                       	       0x1046e4139 0x104679000 + 438585
1   wikimed                       	       0x1046e4938 0x104679000 + 440632
2   Foundation                    	    0x7ff81418797f __NSOPERATION_IS_INVOKING_MAIN__ + 17
3   Foundation                    	    0x7ff814186beb -[NSOperation start] + 785
4   Foundation                    	    0x7ff8141868c1 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 17
5   Foundation                    	    0x7ff814186798 __NSOQSchedule_f + 182
6   libdispatch.dylib             	    0x7ff8130d73c0 _dispatch_block_async_invoke2 + 83
7   libdispatch.dylib             	    0x7ff8130ca317 _dispatch_client_callout + 8
8   libdispatch.dylib             	    0x7ff8130ccd7c _dispatch_continuation_pop + 453
9   libdispatch.dylib             	    0x7ff8130cc43f _dispatch_async_redirect_invoke + 704
10  libdispatch.dylib             	    0x7ff8130d9ac2 _dispatch_root_queue_drain + 343
11  libdispatch.dylib             	    0x7ff8130da25c _dispatch_worker_thread2 + 160
12  libsystem_pthread.dylib       	    0x7ff81327ef8a _pthread_wqthread + 256
13  libsystem_pthread.dylib       	    0x7ff81327df57 start_wqthread + 15

Thread 9:
0   libsystem_pthread.dylib       	    0x7ff81327df48 start_wqthread + 0

Thread 10:
0   libsystem_pthread.dylib       	    0x7ff81327df48 start_wqthread + 0

Thread 8 crashed with X86 Thread State (64-bit):
  rax: 0x00007faec3269920  rbx: 0x1232b65da4848d2d  rcx: 0x00000000b3d91907  rdx: 0x0000000000000001
  rdi: 0x0000700008c8f3f0  rsi: 0x000060000227cdb0  rbp: 0x0000700008c8fca0  rsp: 0x0000700008c8fb30
   r8: 0x0000000000000db0   r9: 0x0000000000000010  r10: 0x00000000000007fb  r11: 0x00000000000003ff
  r12: 0x00007faec322e2b0  r13: 0x00007ff85615d8a8  r14: 0x0000000000000061  r15: 0xe100000000000000
  rip: 0x00000001046e4139  rfl: 0x0000000000010202  cr2: 0x0000000000000000
  
Logical CPU:     2
Error Code:      0x00000000 
Trap Number:     6

Thread 8 instruction stream:
  ff d7 4c 89 f7 e8 0b b5-27 00 48 8d 35 26 6b 29  ..L.....'.H.5&k)
  00 31 ff ba 72 00 00 00-b9 40 00 00 00 41 b8 18  .1..r....@...A..
  00 00 00 41 b9 01 00 00-00 e8 43 bc 27 00 84 c0  ...A......C.'...
  0f 84 06 ff ff ff 0f 0b-48 8d 3d 20 cd 3f 00 e8  ........H.= .?..
  8d b3 27 00 0f 0b 0f 0b-0f 0b 0f 0b 0f 0b 0f 0b  ..'.............
  0f 0b 0f 0b 0f 0b 0f 0b-0f 0b 0f 0b 0f 0b 0f 0b  ................
 [0f]0b 0f 0b 0f 0b 0f 0b-0f 0b 66 66 66 66 2e 0f  ..........ffff..	<==
  1f 84 00 00 00 00 00 55-48 89 e5 41 57 41 56 41  .......UH..AWAVA
  55 41 54 53 48 81 ec c8-00 00 00 48 89 4d c8 41  UATSH......H.M.A
  89 d4 49 89 f5 48 89 7d-c0 31 ff e8 cb a0 27 00  ..I..H.}.1....'.
  49 89 c7 48 8b 40 f8 48-89 45 d0 48 8b 48 40 48  I..H.@.H.E.H.H@H
  89 c8 e8 10 4e fa ff 48-83 c0 0f 48 83 e0 f0 48  ....N..H...H...H

Binary Images:
    0x7ff813244000 -     0x7ff81327bfff libsystem_kernel.dylib (*) <5bbc2e64-012e-34dd-8c02-41294a3d66e9> /usr/lib/system/libsystem_kernel.dylib
    0x7ff8132c9000 -     0x7ff8137cbfff com.apple.CoreFoundation (6.9) <fb79a14a-fda9-3a3b-bc97-6eb525b794a6> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7ff81bfc6000 -     0x7ff81c2b9fff com.apple.HIToolbox (2.1.1) <913d3d2e-4e4c-3907-98fe-8f4abd551297> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
    0x7ff815d43000 -     0x7ff816bd2fff com.apple.AppKit (6.9) <461a4d7c-b3e3-3cbc-92b7-a2a419007281> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7ff91e816000 -     0x7ff91f6b5fff com.apple.SwiftUI (3.5.2) <74cc3179-d95c-3731-868a-adb12816fb15> /System/Library/Frameworks/SwiftUI.framework/Versions/A/SwiftUI
       0x104679000 -        0x104ad8fff org.kiwix.wikimed (1023.12.2) <9df9a416-b187-38e4-801b-90a0d95f5761> /Applications/wikimed.app/Contents/MacOS/wikimed
       0x11462f000 -        0x11469afff dyld (*) <771e1916-3a62-34cd-8488-c1021053c7fa> /usr/lib/dyld
    0x7ff81327c000 -     0x7ff813287fff libsystem_pthread.dylib (*) <e097f78f-fcfb-30f3-9164-dbc9709ba134> /usr/lib/system/libsystem_pthread.dylib
    0x7ff82ba58000 -     0x7ff82d06bfff com.apple.JavaScriptCore (17613) <9bd5e2cc-0c81-3944-84b0-4be54a33fa40> /System/Library/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore
    0x7ff81a3f5000 -     0x7ff81a707fff com.apple.QuartzCore (1.11) <735899b8-b225-34c0-bf33-ee96da0dc64f> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7ff814146000 -     0x7ff814502fff com.apple.Foundation (6.9) <42cdd517-7f3b-3c5e-8ac1-ce7477ac31db> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7ff8130c7000 -     0x7ff81310dfff libdispatch.dylib (*) <85c90f84-c537-3cc6-b795-a066e050ffe3> /usr/lib/system/libdispatch.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.2G resident=0K(0%) swapped_out_or_unallocated=1.2G(100%)
Writable regions: Total=862.0M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=862.0M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               640K        5 
Activity Tracing                   256K        1 
CG backing stores                 1440K        8 
CG image                            92K       11 
ColorSync                          224K       27 
CoreAnimation                      348K       38 
CoreData Object IDs               4100K        2 
CoreGraphics                        12K        3 
CoreUI image data                  708K       13 
Foundation                          44K        2 
IOKit                             15.5M        2 
Kernel Alloc Once                    8K        1 
MALLOC                           260.3M       77 
MALLOC guard page                   32K        8 
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
SQLite page cache                  256K        4 
STACK GUARD                       56.0M       11 
Stack                             13.6M       11 
VM_ALLOCATE                       3200K       22 
WebKit Malloc                    192.0M        4 
__CTF                               756        1 
__DATA                            31.6M      548 
__DATA_CONST                      32.5M      367 
__DATA_DIRTY                      1989K      227 
__FONT_DATA                          4K        1 
__GLSLBUILTINS                    5176K        1 
__LINKEDIT                       646.6M        9 
__OBJC_RO                         82.9M        1 
__OBJC_RW                         3200K        2 
__TEXT                           542.6M      563 
__UNICODE                          592K        1 
dyld private memory               1024K        1 
mapped file                      223.4M       35 
shared memory                     2824K       17 
===========                     =======  ======= 
TOTAL                              2.4G     2025 
TOTAL, minus reserved VM space     2.1G     2025 

-----------
Full Report
-----------

{"app_cohort":"2|date=1705937400000&sf=143442&tid=8ab3ef9c11117097e3e0277f4db25075cee64efec5ca8562a6fa9e67f99ebd07&ttype=i","app_name":"wikimed","app_version":"1023.12.2","timestamp":"2024-01-23 08:25:08.00 +0100","slice_uuid":"9df9a416-b187-38e4-801b-90a0d95f5761","adam_id":"1281693200","build_version":"133","platform":1,"bundleID":"org.kiwix.wikimed","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.7.1 (21G920)","incident_id":"AE3A6B00-D049-4C5C-AB07-97C981E17C6E","name":"wikimed","is_beta":1}
{
  "uptime" : 1100000,
  "procLaunch" : "2024-01-23 08:25:01.7689 +0100",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro11,4",
  "procStartAbsTime" : 1121817529648615,
  "coalitionID" : 93130,
  "osVersion" : {
    "train" : "macOS 12.7.1",
    "build" : "21G920",
    "releaseType" : "User"
  },
  "captureTime" : "2024-01-23 08:25:07.6736 +0100",
  "incident" : "AE3A6B00-D049-4C5C-AB07-97C981E17C6E",
  "bug_type" : "309",
  "pid" : 14000,
  "procExitAbsTime" : 1121823430973069,
  "cpuType" : "X86-64",
  "procName" : "wikimed",
  "procPath" : "\/Applications\/wikimed.app\/Contents\/MacOS\/wikimed",
  "bundleInfo" : {"CFBundleShortVersionString":"1023.12.2","CFBundleVersion":"133","CFBundleIdentifier":"org.kiwix.wikimed"},
  "storeInfo" : {"storeCohortMetadata":"2|date=1705937400000&sf=143442&tid=8ab3ef9c11117097e3e0277f4db25075cee64efec5ca8562a6fa9e67f99ebd07&ttype=i","itemID":"1281693200","deviceIdentifierForVendor":"C2B9E535-041A-5032-9AB4-F53CA09D715D","thirdParty":true,"entitledBeta":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "org.kiwix.wikimed",
  "isBeta" : 1,
  "wakeTime" : 60294,
  "sleepWakeUUID" : "EAE0649E-F1CE-46CE-8072-39A0E41B875B",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x0000000000000000","rawCodes":[1,0],"type":"EXC_BAD_INSTRUCTION","signal":"SIGILL"},
  "termination" : {"flags":0,"code":4,"namespace":"SIGNAL","indicator":"Illegal instruction: 4","byProc":"exc handler","byPid":14000},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 8,
  "threads" : [{"id":10699405,"queue":"com.apple.main-thread","frames":[{"imageOffset":6506,"symbol":"mach_msg_trap","symbolLocation":10,"imageIndex":0},{"imageOffset":7384,"symbol":"mach_msg","symbolLocation":56,"imageIndex":0},{"imageOffset":524957,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":319,"imageIndex":1},{"imageOffset":518440,"symbol":"__CFRunLoopRun","symbolLocation":1276,"imageIndex":1},{"imageOffset":515436,"symbol":"CFRunLoopRunSpecific","symbolLocation":562,"imageIndex":1},{"imageOffset":189926,"symbol":"RunCurrentEventLoopInMode","symbolLocation":292,"imageIndex":2},{"imageOffset":189258,"symbol":"ReceiveNextEventCommon","symbolLocation":594,"imageIndex":2},{"imageOffset":188645,"symbol":"_BlockUntilNextEventMatchingListInModeWithFilter","symbolLocation":70,"imageIndex":2},{"imageOffset":257901,"symbol":"_DPSNextEvent","symbolLocation":927,"imageIndex":3},{"imageOffset":251434,"symbol":"-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]","symbolLocation":1394,"imageIndex":3},{"imageOffset":195801,"symbol":"-[NSApplication run]","symbolLocation":586,"imageIndex":3},{"imageOffset":15447,"symbol":"NSApplicationMain","symbolLocation":817,"imageIndex":3},{"imageOffset":508060,"symbol":"specialized runApp(_:)","symbolLocation":161,"imageIndex":4},{"imageOffset":11396132,"symbol":"runApp<A>(_:)","symbolLocation":164,"imageIndex":4},{"imageOffset":6122591,"symbol":"static App.main()","symbolLocation":63,"imageIndex":4},{"imageOffset":94622,"imageIndex":5},{"imageOffset":21806,"symbol":"start","symbolLocation":462,"imageIndex":6}]},{"id":10699422,"frames":[{"imageOffset":8008,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":10699433,"frames":[{"imageOffset":8008,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":10699440,"name":"JavaScriptCore libpas scavenger","frames":[{"imageOffset":17370,"symbol":"__psynch_cvwait","symbolLocation":10,"imageIndex":0},{"imageOffset":27247,"symbol":"_pthread_cond_wait","symbolLocation":1249,"imageIndex":7},{"imageOffset":2518821,"symbol":"scavenger_thread_main","symbolLocation":1397,"imageIndex":8},{"imageOffset":25825,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":7},{"imageOffset":8043,"symbol":"thread_start","symbolLocation":15,"imageIndex":7}]},{"id":10699445,"name":"com.apple.NSEventThread","frames":[{"imageOffset":6506,"symbol":"mach_msg_trap","symbolLocation":10,"imageIndex":0},{"imageOffset":7384,"symbol":"mach_msg","symbolLocation":56,"imageIndex":0},{"imageOffset":524957,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":319,"imageIndex":1},{"imageOffset":518440,"symbol":"__CFRunLoopRun","symbolLocation":1276,"imageIndex":1},{"imageOffset":515436,"symbol":"CFRunLoopRunSpecific","symbolLocation":562,"imageIndex":1},{"imageOffset":1755534,"symbol":"_NSEventThread","symbolLocation":132,"imageIndex":3},{"imageOffset":25825,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":7},{"imageOffset":8043,"symbol":"thread_start","symbolLocation":15,"imageIndex":7}]},{"id":10699448,"name":"com.apple.coreanimation.render-server","frames":[{"imageOffset":6506,"symbol":"mach_msg_trap","symbolLocation":10,"imageIndex":0},{"imageOffset":7384,"symbol":"mach_msg","symbolLocation":56,"imageIndex":0},{"imageOffset":293447,"symbol":"CA::Render::Server::server_thread(void*)","symbolLocation":534,"imageIndex":9},{"imageOffset":292902,"symbol":"thread_fun(void*)","symbolLocation":25,"imageIndex":9},{"imageOffset":25825,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":7},{"imageOffset":8043,"symbol":"thread_start","symbolLocation":15,"imageIndex":7}]},{"id":10699455,"frames":[{"imageOffset":8008,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":10699496,"frames":[{"imageOffset":8008,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"triggered":true,"id":10699498,"instructionState":{"instructionStream":{"bytes":[255,215,76,137,247,232,11,181,39,0,72,141,53,38,107,41,0,49,255,186,114,0,0,0,185,64,0,0,0,65,184,24,0,0,0,65,185,1,0,0,0,232,67,188,39,0,132,192,15,132,6,255,255,255,15,11,72,141,61,32,205,63,0,232,141,179,39,0,15,11,15,11,15,11,15,11,15,11,15,11,15,11,15,11,15,11,15,11,15,11,15,11,15,11,15,11,15,11,15,11,15,11,15,11,15,11,102,102,102,102,46,15,31,132,0,0,0,0,0,85,72,137,229,65,87,65,86,65,85,65,84,83,72,129,236,200,0,0,0,72,137,77,200,65,137,212,73,137,245,72,137,125,192,49,255,232,203,160,39,0,73,137,199,72,139,64,248,72,137,69,208,72,139,72,64,72,137,200,232,16,78,250,255,72,131,192,15,72,131,224,240,72],"offset":96}},"threadState":{"r13":{"value":140704572889256,"symbolLocation":0,"symbol":"value witness table for Builtin.Int64"},"rax":{"value":140388575123744},"rflags":{"value":66050},"cpu":{"value":2},"r14":{"value":97},"rsi":{"value":105553152429488},"r8":{"value":3504},"cr2":{"value":0},"rdx":{"value":1},"r10":{"value":2043},"r9":{"value":16},"r15":{"value":16212958658533785600},"rbx":{"value":1311310954826599725},"trap":{"value":6},"err":{"value":0},"r11":{"value":1023},"rip":{"value":4369301817,"matchesCrashFrame":1},"rbp":{"value":123145449700512},"rsp":{"value":123145449700144},"r12":{"value":140388574880432},"rcx":{"value":3017349383},"flavor":"x86_THREAD_STATE","rdi":{"value":123145449698288}},"queue":"NSOperationQueue 0x7faec3159290 (QOS: UNSPECIFIED)","frames":[{"imageOffset":438585,"imageIndex":5},{"imageOffset":440632,"imageIndex":5},{"imageOffset":268671,"symbol":"__NSOPERATION_IS_INVOKING_MAIN__","symbolLocation":17,"imageIndex":10},{"imageOffset":265195,"symbol":"-[NSOperation start]","symbolLocation":785,"imageIndex":10},{"imageOffset":264385,"symbol":"__NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__","symbolLocation":17,"imageIndex":10},{"imageOffset":264088,"symbol":"__NSOQSchedule_f","symbolLocation":182,"imageIndex":10},{"imageOffset":66496,"symbol":"_dispatch_block_async_invoke2","symbolLocation":83,"imageIndex":11},{"imageOffset":13079,"symbol":"_dispatch_client_callout","symbolLocation":8,"imageIndex":11},{"imageOffset":23932,"symbol":"_dispatch_continuation_pop","symbolLocation":453,"imageIndex":11},{"imageOffset":21567,"symbol":"_dispatch_async_redirect_invoke","symbolLocation":704,"imageIndex":11},{"imageOffset":76482,"symbol":"_dispatch_root_queue_drain","symbolLocation":343,"imageIndex":11},{"imageOffset":78428,"symbol":"_dispatch_worker_thread2","symbolLocation":160,"imageIndex":11},{"imageOffset":12170,"symbol":"_pthread_wqthread","symbolLocation":256,"imageIndex":7},{"imageOffset":8023,"symbol":"start_wqthread","symbolLocation":15,"imageIndex":7}]},{"id":10699500,"frames":[{"imageOffset":8008,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":10699501,"frames":[{"imageOffset":8008,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703449759744,
    "size" : 229376,
    "uuid" : "5bbc2e64-012e-34dd-8c02-41294a3d66e9",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64h",
    "base" : 140703450304512,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5255168,
    "uuid" : "fb79a14a-fda9-3a3b-bc97-6eb525b794a6",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1866"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703598141440,
    "CFBundleShortVersionString" : "2.1.1",
    "CFBundleIdentifier" : "com.apple.HIToolbox",
    "size" : 3096576,
    "uuid" : "913d3d2e-4e4c-3907-98fe-8f4abd551297",
    "path" : "\/System\/Library\/Frameworks\/Carbon.framework\/Versions\/A\/Frameworks\/HIToolbox.framework\/Versions\/A\/HIToolbox",
    "name" : "HIToolbox"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703494844416,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15269888,
    "uuid" : "461a4d7c-b3e3-3cbc-92b7-a2a419007281",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2113.60.148"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140707935379456,
    "CFBundleShortVersionString" : "3.5.2",
    "CFBundleIdentifier" : "com.apple.SwiftUI",
    "size" : 15335424,
    "uuid" : "74cc3179-d95c-3731-868a-adb12816fb15",
    "path" : "\/System\/Library\/Frameworks\/SwiftUI.framework\/Versions\/A\/SwiftUI",
    "name" : "SwiftUI",
    "CFBundleVersion" : "3.5.2"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4368863232,
    "CFBundleShortVersionString" : "1023.12.2",
    "CFBundleIdentifier" : "org.kiwix.wikimed",
    "size" : 4587520,
    "uuid" : "9df9a416-b187-38e4-801b-90a0d95f5761",
    "path" : "\/Applications\/wikimed.app\/Contents\/MacOS\/wikimed",
    "name" : "wikimed",
    "CFBundleVersion" : "133"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4636995584,
    "size" : 442368,
    "uuid" : "771e1916-3a62-34cd-8488-c1021053c7fa",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703449989120,
    "size" : 49152,
    "uuid" : "e097f78f-fcfb-30f3-9164-dbc9709ba134",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703860883456,
    "CFBundleShortVersionString" : "17613",
    "CFBundleIdentifier" : "com.apple.JavaScriptCore",
    "size" : 23150592,
    "uuid" : "9bd5e2cc-0c81-3944-84b0-4be54a33fa40",
    "path" : "\/System\/Library\/Frameworks\/JavaScriptCore.framework\/Versions\/A\/JavaScriptCore",
    "name" : "JavaScriptCore",
    "CFBundleVersion" : "17613.3.9.1.16"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703568973824,
    "CFBundleShortVersionString" : "1.11",
    "CFBundleIdentifier" : "com.apple.QuartzCore",
    "size" : 3223552,
    "uuid" : "735899b8-b225-34c0-bf33-ee96da0dc64f",
    "path" : "\/System\/Library\/Frameworks\/QuartzCore.framework\/Versions\/A\/QuartzCore",
    "name" : "QuartzCore",
    "CFBundleVersion" : "964.37"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703465496576,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.Foundation",
    "size" : 3919872,
    "uuid" : "42cdd517-7f3b-3c5e-8ac1-ce7477ac31db",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Versions\/C\/Foundation",
    "name" : "Foundation",
    "CFBundleVersion" : "1866"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703448199168,
    "size" : 290816,
    "uuid" : "85c90f84-c537-3cc6-b795-a066e050ffe3",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  }
],
  "sharedCache" : {
  "base" : 140703446728704,
  "size" : 19331678208,
  "uuid" : "172bd7f4-7e24-3286-a975-45e4e44c23c1"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.2G resident=0K(0%) swapped_out_or_unallocated=1.2G(100%)\nWritable regions: Total=862.0M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=862.0M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               640K        5 \nActivity Tracing                   256K        1 \nCG backing stores                 1440K        8 \nCG image                            92K       11 \nColorSync                          224K       27 \nCoreAnimation                      348K       38 \nCoreData Object IDs               4100K        2 \nCoreGraphics                        12K        3 \nCoreUI image data                  708K       13 \nFoundation                          44K        2 \nIOKit                             15.5M        2 \nKernel Alloc Once                    8K        1 \nMALLOC                           260.3M       77 \nMALLOC guard page                   32K        8 \nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSQLite page cache                  256K        4 \nSTACK GUARD                       56.0M       11 \nStack                             13.6M       11 \nVM_ALLOCATE                       3200K       22 \nWebKit Malloc                    192.0M        4 \n__CTF                               756        1 \n__DATA                            31.6M      548 \n__DATA_CONST                      32.5M      367 \n__DATA_DIRTY                      1989K      227 \n__FONT_DATA                          4K        1 \n__GLSLBUILTINS                    5176K        1 \n__LINKEDIT                       646.6M        9 \n__OBJC_RO                         82.9M        1 \n__OBJC_RW                         3200K        2 \n__TEXT                           542.6M      563 \n__UNICODE                          592K        1 \ndyld private memory               1024K        1 \nmapped file                      223.4M       35 \nshared memory                     2824K       17 \n===========                     =======  ======= \nTOTAL                              2.4G     2025 \nTOTAL, minus reserved VM space     2.1G     2025 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "NSOperationQueue 0x7faec3159290 (QOS: UNSPECIFIED)"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60f8ddccefea4203d95cbeef",
      "factorPackIds" : {
        "NETWORK_SERVICE_PROXY_CONFIG_UPDATE" : "6401414cc679dd6bc5828183"
      },
      "deploymentId" : 240000025
    },
    {
      "rolloutId" : "5f72dc58705eff005a46b3a9",
      "factorPackIds" : {

      },
      "deploymentId" : 240000015
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro11,4, BootROM 486.0.0.0.0, 4 processors, Quad-Core Intel Core i7, 2,2 GHz, 16 GB, SMC 2.29f24
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Display: LEN T2324pA, 1920 x 1080 (1080p FHD - Full High Definition), Main, MirrorOff, Online
Display: LEN T2324pA, 1920 x 1080 (1080p FHD - Full High Definition), MirrorOff, Online
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x152), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1710.4)
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0512G, 500,28 GB
USB Device: USB30Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Bluetooth USB Host Controller
USB Device: USB2.0 Hub
USB Device: USB2.0 Hub
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1

</details>

### PR DESCRIPTION
**Pull request by BPerlakiH**
Fixes #635
Fixes #631

The wikimed custom app was crashing if the user did any search.

# Solution
Use a similar implementation as on Android, to avoid errors to be thrown when the search result has an empty title.
Filter out any empty titles, as they won't be useful for the end user (it creates blank lines in search results).

### CODE REVIEW

**Review by benoit74 — CHANGES_REQUESTED** [review]
While useful (an error here shouldn't make the application crash), I think it is not sufficient, this does not fix the underlying issue, you should:
- log the exception as well
- find the underlying issue and fix it (reproduction is pretty easy and a clear log with the exception should permit you to know what is going on, or at least have some clues)

**Comment by rgaudin** [comment]
I agree with @benoit74 ; this justs prevent a crash but is misleading user into thinking there's no search results while it's not the case and we have no idea what's going on so no chance to fix it.

**Comment by BPerlakiH** [comment]
I see your point. 
Actually we have number of similar try catches around the code, so I thought it should be OK.

To clarify things further: **there are search results**, but some of them are failing, therefore it was crashing.
This is the stack trace, I can see:

```
wikimed`zim::Archive::getEntryByPath:
    0x104c0bc5c <+0>:   sub    sp, sp, #0xa0
    0x104c0bc60 <+4>:   stp    x24, x23, [sp, #0x60]
    0x104c0bc64 <+8>:   stp    x22, x21, [sp, #0x70]
    0x104c0bc68 <+12>:  stp    x20, x19, [sp, #0x80]
    0x104c0bc6c <+16>:  stp    x29, x30, [sp, #0x90]
    0x104c0bc70 <+20>:  add    x29, sp, #0x90
    0x104c0bc74 <+24>:  mov    x21, x1
    0x104c0bc78 <+28>:  mov    x20, x0
    0x104c0bc7c <+32>:  mov    x19, x8
    0x104c0bc80 <+36>:  ldr    x0, [x0]
    0x104c0bc84 <+40>:  ldrb   w8, [x0, #0x120]
    0x104c0bc88 <+44>:  cbz    w8, 0x104c0bcec           ; <+144>
    0x104c0bc8c <+48>:  mov    w1, #0x43
    0x104c0bc90 <+52>:  mov    x2, x21
    0x104c0bc94 <+56>:  bl     0x104c16848               ; zim::FileImpl::findx(char, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)
    0x104c0bc98 <+60>:  ldr    x22, [x20]
    0x104c0bc9c <+64>:  tst    w0, #0xff
    0x104c0bca0 <+68>:  b.eq   0x104c0bd38               ; <+220>
    0x104c0bca4 <+72>:  ldr    x8, [x20, #0x8]
    0x104c0bca8 <+76>:  lsr    x2, x0, #8
    0x104c0bcac <+80>:  stp    x22, x8, [x29, #-0x40]
    0x104c0bcb0 <+84>:  cbz    x8, 0x104c0bcc0           ; <+100>
    0x104c0bcb4 <+88>:  add    x8, x8, #0x8
    0x104c0bcb8 <+92>:  mov    w9, #0x1
    0x104c0bcbc <+96>:  ldadd  x9, x8, [x8]
    0x104c0bcc0 <+100>: sub    x1, x29, #0x40
    0x104c0bcc4 <+104>: mov    x0, x19
    0x104c0bcc8 <+108>: bl     0x104c1219c               ; zim::Entry::Entry(std::__1::shared_ptr<zim::FileImpl>, unsigned int)
    0x104c0bccc <+112>: ldur   x19, [x29, #-0x38]
    0x104c0bcd0 <+116>: cbnz   x19, 0x104c0bdec          ; <+400>
    0x104c0bcd4 <+120>: ldp    x29, x30, [sp, #0x90]
    0x104c0bcd8 <+124>: ldp    x20, x19, [sp, #0x80]
    0x104c0bcdc <+128>: ldp    x22, x21, [sp, #0x70]
    0x104c0bce0 <+132>: ldp    x24, x23, [sp, #0x60]
    0x104c0bce4 <+136>: add    sp, sp, #0xa0
    0x104c0bce8 <+140>: ret    
    0x104c0bcec <+144>: mov    x1, x21
    0x104c0bcf0 <+148>: bl     0x104c16874               ; zim::FileImpl::findx(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)
    0x104c0bcf4 <+152>: mov    x8, x0
    0x104c0bcf8 <+156>: ldr    x0, [x20]
    0x104c0bcfc <+160>: tst    w8, #0xff
    0x104c0bd00 <+164>: b.eq   0x104c0bda8               ; <+332>
    0x104c0bd04 <+168>: ldr    x9, [x20, #0x8]
    0x104c0bd08 <+172>: lsr    x2, x8, #8
    0x104c0bd0c <+176>: stp    x0, x9, [sp, #0x10]
    0x104c0bd10 <+180>: cbz    x9, 0x104c0bd20           ; <+196>
    0x104c0bd14 <+184>: add    x8, x9, #0x8
    0x104c0bd18 <+188>: mov    w9, #0x1
    0x104c0bd1c <+192>: ldadd  x9, x8, [x8]
    0x104c0bd20 <+196>: add    x1, sp, #0x10
    0x104c0bd24 <+200>: mov    x0, x19
    0x104c0bd28 <+204>: bl     0x104c1219c               ; zim::Entry::Entry(std::__1::shared_ptr<zim::FileImpl>, unsigned int)
    0x104c0bd2c <+208>: ldr    x19, [sp, #0x18]
    0x104c0bd30 <+212>: cbnz   x19, 0x104c0bdec          ; <+400>
    0x104c0bd34 <+216>: b      0x104c0bcd4               ; <+120>
    0x104c0bd38 <+220>: add    x23, sp, #0x30
    0x104c0bd3c <+224>: add    x8, sp, #0x30
    0x104c0bd40 <+228>: mov    x0, x21
    0x104c0bd44 <+232>: bl     0x104c22e1c               ; zim::parseLongPath(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)
    0x104c0bd48 <+236>: add    x2, x23, #0x8
    0x104c0bd4c <+240>: mov    x0, x22
    0x104c0bd50 <+244>: mov    w1, #0x43
    0x104c0bd54 <+248>: bl     0x104c16848               ; zim::FileImpl::findx(char, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)
    0x104c0bd58 <+252>: mov    x21, x0
    0x104c0bd5c <+256>: ldrsb  w8, [sp, #0x4f]
    0x104c0bd60 <+260>: tbz    w8, #0x1f, 0x104c0bd6c    ; <+272>
    0x104c0bd64 <+264>: ldr    x0, [sp, #0x38]
    0x104c0bd68 <+268>: bl     0x104e0ebb0               ; symbol stub for: operator delete(void*)
    0x104c0bd6c <+272>: tst    w21, #0xff
    0x104c0bd70 <+276>: b.eq   0x104c0bee0               ; <+644>
    0x104c0bd74 <+280>: lsr    x2, x21, #8
    0x104c0bd78 <+284>: ldp    x9, x8, [x20]
    0x104c0bd7c <+288>: stp    x9, x8, [sp, #0x20]
    0x104c0bd80 <+292>: cbz    x8, 0x104c0bd90           ; <+308>
    0x104c0bd84 <+296>: add    x8, x8, #0x8
    0x104c0bd88 <+300>: mov    w9, #0x1
    0x104c0bd8c <+304>: ldadd  x9, x8, [x8]
    0x104c0bd90 <+308>: add    x1, sp, #0x20
    0x104c0bd94 <+312>: mov    x0, x19
    0x104c0bd98 <+316>: bl     0x104c1219c               ; zim::Entry::Entry(std::__1::shared_ptr<zim::FileImpl>, unsigned int)
    0x104c0bd9c <+320>: ldr    x19, [sp, #0x28]
    0x104c0bda0 <+324>: cbnz   x19, 0x104c0bdec          ; <+400>
    0x104c0bda4 <+328>: b      0x104c0bcd4               ; <+120>
    0x104c0bda8 <+332>: mov    w1, #0x41
    0x104c0bdac <+336>: mov    x2, x21
    0x104c0bdb0 <+340>: bl     0x104c16848               ; zim::FileImpl::findx(char, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)
    0x104c0bdb4 <+344>: tst    w0, #0xff
    0x104c0bdb8 <+348>: b.eq   0x104c0be2c               ; <+464>
    0x104c0bdbc <+352>: lsr    x2, x0, #8
    0x104c0bdc0 <+356>: ldp    x9, x8, [x20]
    0x104c0bdc4 <+360>: stp    x9, x8, [sp]
    0x104c0bdc8 <+364>: cbz    x8, 0x104c0bdd8           ; <+380>
    0x104c0bdcc <+368>: add    x8, x8, #0x8
    0x104c0bdd0 <+372>: mov    w9, #0x1
    0x104c0bdd4 <+376>: ldadd  x9, x8, [x8]
    0x104c0bdd8 <+380>: mov    x1, sp
    0x104c0bddc <+384>: mov    x0, x19
    0x104c0bde0 <+388>: bl     0x104c1219c               ; zim::Entry::Entry(std::__1::shared_ptr<zim::FileImpl>, unsigned int)
    0x104c0bde4 <+392>: ldr    x19, [sp, #0x8]
    0x104c0bde8 <+396>: cbz    x19, 0x104c0bcd4          ; <+120>
    0x104c0bdec <+400>: add    x8, x19, #0x8
    0x104c0bdf0 <+404>: mov    x9, #-0x1
    0x104c0bdf4 <+408>: ldaddal x9, x8, [x8]
    0x104c0bdf8 <+412>: cbnz   x8, 0x104c0bcd4           ; <+120>
    0x104c0bdfc <+416>: ldr    x8, [x19]
    0x104c0be00 <+420>: ldr    x8, [x8, #0x10]
    0x104c0be04 <+424>: mov    x0, x19
    0x104c0be08 <+428>: blr    x8
    0x104c0be0c <+432>: mov    x0, x19
    0x104c0be10 <+436>: bl     0x104e0e6e8               ; symbol stub for: std::__1::__shared_weak_count::__release_weak()
    0x104c0be14 <+440>: ldp    x29, x30, [sp, #0x90]
    0x104c0be18 <+444>: ldp    x20, x19, [sp, #0x80]
    0x104c0be1c <+448>: ldp    x22, x21, [sp, #0x70]
    0x104c0be20 <+452>: ldp    x24, x23, [sp, #0x60]
    0x104c0be24 <+456>: add    sp, sp, #0xa0
    0x104c0be28 <+460>: ret    
    0x104c0be2c <+464>: ldr    x0, [x20]
    0x104c0be30 <+468>: mov    w1, #0x49
    0x104c0be34 <+472>: mov    x2, x21
    0x104c0be38 <+476>: bl     0x104c16848               ; zim::FileImpl::findx(char, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)
    0x104c0be3c <+480>: tst    w0, #0xff
    0x104c0be40 <+484>: b.ne   0x104c0be74               ; <+536>
    0x104c0be44 <+488>: ldr    x0, [x20]
    0x104c0be48 <+492>: mov    w1, #0x4a
    0x104c0be4c <+496>: mov    x2, x21
    0x104c0be50 <+500>: bl     0x104c16848               ; zim::FileImpl::findx(char, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)
    0x104c0be54 <+504>: tst    w0, #0xff
    0x104c0be58 <+508>: b.ne   0x104c0be74               ; <+536>
    0x104c0be5c <+512>: ldr    x0, [x20]
    0x104c0be60 <+516>: mov    w1, #0x2d
    0x104c0be64 <+520>: mov    x2, x21
    0x104c0be68 <+524>: bl     0x104c16848               ; zim::FileImpl::findx(char, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)
    0x104c0be6c <+528>: tst    w0, #0xff
    0x104c0be70 <+532>: b.eq   0x104c0bee0               ; <+644>
    0x104c0be74 <+536>: lsr    x2, x0, #8
    0x104c0be78 <+540>: ldp    x9, x8, [x20]
    0x104c0be7c <+544>: stp    x9, x8, [sp]
    0x104c0be80 <+548>: cbnz   x8, 0x104c0bdcc           ; <+368>
    0x104c0be84 <+552>: b      0x104c0bdd8               ; <+380>
    0x104c0be88 <+556>: mov    x19, x0
    0x104c0be8c <+560>: mov    x0, sp
    0x104c0be90 <+564>: b      0x104c0bf88               ; <+812>
    0x104c0be94 <+568>: mov    x20, x1
    0x104c0be98 <+572>: mov    x19, x0
    0x104c0be9c <+576>: add    x0, sp, #0x20
    0x104c0bea0 <+580>: bl     0x10450898c               ; std::__1::shared_ptr<zim::FileImpl>::~shared_ptr[abi:v160006] at shared_ptr.h:743
    0x104c0bea4 <+584>: b      0x104c0becc               ; <+624>
    0x104c0bea8 <+588>: mov    x20, x1
    0x104c0beac <+592>: mov    x19, x0
    0x104c0beb0 <+596>: ldrsb  w8, [sp, #0x4f]
    0x104c0beb4 <+600>: tbz    w8, #0x1f, 0x104c0becc    ; <+624>
    0x104c0beb8 <+604>: ldr    x0, [sp, #0x38]
    0x104c0bebc <+608>: bl     0x104e0ebb0               ; symbol stub for: operator delete(void*)
    0x104c0bec0 <+612>: b      0x104c0becc               ; <+624>
    0x104c0bec4 <+616>: mov    x20, x1
    0x104c0bec8 <+620>: mov    x19, x0
    0x104c0becc <+624>: cmp    w20, #0x1
    0x104c0bed0 <+628>: b.ne   0x104c0bf8c               ; <+816>
    0x104c0bed4 <+632>: mov    x0, x19
    0x104c0bed8 <+636>: bl     0x104e0e8d4               ; symbol stub for: __cxa_begin_catch
    0x104c0bedc <+640>: bl     0x104e0ea3c               ; symbol stub for: __cxa_end_catch
    0x104c0bee0 <+644>: mov    w0, #0x10
    0x104c0bee4 <+648>: bl     0x104e0eafc               ; symbol stub for: __cxa_allocate_exception
    0x104c0bee8 <+652>: mov    x20, x0
    0x104c0beec <+656>: adrp   x1, 627
    0x104c0bef0 <+660>: add    x1, x1, #0xf8e            ; "Cannot find entry"
    0x104c0bef4 <+664>: add    x0, sp, #0x30
    0x104c0bef8 <+668>: bl     0x1044f2910               ; std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::basic_string[abi:v160006]<std::nullptr_t> at string:880
    0x104c0befc <+672>: mov    w21, #0x1
    0x104c0bf00 <+676>: add    x1, sp, #0x30
    0x104c0bf04 <+680>: mov    x0, x20
    0x104c0bf08 <+684>: bl     0x104e0ea24               ; symbol stub for: std::runtime_error::runtime_error(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)
    0x104c0bf0c <+688>: adrp   x8, 2979
    0x104c0bf10 <+692>: add    x8, x8, #0xae0            ; vtable for zim::EntryNotFound
    0x104c0bf14 <+696>: add    x8, x8, #0x10
    0x104c0bf18 <+700>: str    x8, [x20]
    0x104c0bf1c <+704>: mov    w21, #0x0
    0x104c0bf20 <+708>: adrp   x1, 2979
    0x104c0bf24 <+712>: add    x1, x1, #0xab0            ; typeinfo for zim::EntryNotFound
    0x104c0bf28 <+716>: adrp   x2, -1
    0x104c0bf2c <+720>: add    x2, x2, #0xf64            ; zim::EntryNotFound::~EntryNotFound()
    0x104c0bf30 <+724>: mov    x0, x20
    0x104c0bf34 <+728>: bl     0x104e0e5e0               ; symbol stub for: __cxa_throw
->  0x104c0bf38 <+732>: brk    #0x1
    0x104c0bf3c <+736>: mov    x19, x0
    0x104c0bf40 <+740>: add    x0, sp, #0x10
    0x104c0bf44 <+744>: b      0x104c0bf88               ; <+812>
    0x104c0bf48 <+748>: mov    x19, x0
    0x104c0bf4c <+752>: ldrsb  w8, [sp, #0x47]
    0x104c0bf50 <+756>: tbz    w8, #0x1f, 0x104c0bf64    ; <+776>
    0x104c0bf54 <+760>: ldr    x0, [sp, #0x30]
    0x104c0bf58 <+764>: bl     0x104e0ebb0               ; symbol stub for: operator delete(void*)
    0x104c0bf5c <+768>: tbnz   w21, #0x0, 0x104c0bf70    ; <+788>
    0x104c0bf60 <+772>: b      0x104c0bf8c               ; <+816>
    0x104c0bf64 <+776>: cbnz   w21, 0x104c0bf70          ; <+788>
    0x104c0bf68 <+780>: b      0x104c0bf8c               ; <+816>
    0x104c0bf6c <+784>: mov    x19, x0
    0x104c0bf70 <+788>: mov    x0, x20
    0x104c0bf74 <+792>: bl     0x104e0e6f4               ; symbol stub for: __cxa_free_exception
    0x104c0bf78 <+796>: mov    x0, x19
    0x104c0bf7c <+800>: bl     0x104e0f618               ; symbol stub for: _Unwind_Resume
    0x104c0bf80 <+804>: mov    x19, x0
    0x104c0bf84 <+808>: sub    x0, x29, #0x40
    0x104c0bf88 <+812>: bl     0x10450898c               ; std::__1::shared_ptr<zim::FileImpl>::~shared_ptr[abi:v160006] at shared_ptr.h:743
    0x104c0bf8c <+816>: mov    x0, x19
    0x104c0bf90 <+820>: bl     0x104e0f618               ; symbol stub for: _Unwind_Resume

```
So it seems to me that from here:
```
/// Add search results based on matching article titles with search text.
/// @param archives archives to retrieve search results from
/// @param count number of articles to retrieve for each archive
- (void)addTitleSearchResults:(std::vector<zim::Archive>)archives count:(int)count {
    for (zim::Archive archive: archives) {
        if (self.isCancelled) { break; }
        
        NSUUID *zimFileID = [[NSUUID alloc] initWithUUIDBytes:(unsigned char *)archive.getUuid().data];
        auto results = zim::SuggestionSearcher(archive).suggest(self.searchText_C).getResults(0, count);
        for (auto result = results.begin(); result != results.end(); result++) {
            if (self.isCancelled) { break; }

            try {
                zim::Entry entry = result.getEntry();  <------- breaks
```
I am no good at C++, but my feeling is that we either run out of bounds somehow as `count` is set to 35,
or some of those entries included are not reachable for some other reasons.

I've attached a list of files, with the log entries (found items, and thrown error spots) for the search term "alpha",
each file with the result as I typed, a, al, alph, alpha:

[a.log](https://github.com/kiwix/apple/files/14044108/a.log)
[al.log](https://github.com/kiwix/apple/files/14044109/al.log)
[alp.log](https://github.com/kiwix/apple/files/14044110/alp.log)
[alph.log](https://github.com/kiwix/apple/files/14044111/alph.log)
[alpha.log](https://github.com/kiwix/apple/files/14044112/alpha.log)

**Comment by BPerlakiH** [comment]
As a short term solution I think this is still a viable option to catch individual items and fall back to a smaller amount of search results, than crashing the app, while we investigate things. What do you think @rgaudin and @benoit74  ?

**Comment by kelson42** [comment]
@BPerlakiH General remarks:
*. Before fixing a problem, the problem should be 100% understood and explained in the issue
* If the solution is not straight, then the way chosen to solve the issue should be explained and proposed first to get feedbacks
* If another piece of software does not work as expected, then an issue should be open in its repository and then we should discuss if it makes sense to work on a workaround until fix is implemented
* each PR has to come with a description telling which issue is fixed, the principle of the fix and the impact for both future devs and end users
* If a software trigger an exception, then something is not normal somewhere. Exceptions do not belong to normal,behaviour of a software. Itˋs last line of defense to attempt sharing information about something disfunctional.

Here, either you believe the libkiwix is buggy and you open a ticket explaining why? Or the root cause is on Swift and it has to be fixed.

We are here to help if something is unclear. Have you tried to look how this works with Kiwix Android? Usually the root of problem is that searches are not thread safe, so you need to be careful to not run two at the same time. Its important to understand as well that custom app ZIM files don't have a fulltext search index.

**Comment by kelson42** [comment]
@rgaudin We should put my general remarks in your coding guidelines if not there already.

**Comment by benoit74** [comment]
> Usually the root of problem is that searches are not thread safe, so you need to be careful to not run two at the same time. Its important to understand as well that custom app ZIM files don't have a fulltext search index.

Here the search is working "sometimes". So the "hot patch" proposed makes sense since it looks like there is a problem only on some (few?) entries returned by the search. But this PR shouldn't mark the issue as fixed.

I would propose to:
- Remove the "Fix #xxx"
- Explain that this is only a hot fix to avoid the search making the app crash completely (because it makes sense to start with this fix, we could even decide to publish the app with only this fix if the underlying cause is complex / time consuming)
- Continue to investigate on the issue as @kelson42 suggested

**Comment by rgaudin** [comment]
> @rgaudin We should put my general remarks in your coding guidelines if not there already.

Updated

**Comment by BPerlakiH** [comment]
@kelson42 @rgaudin @benoit74 
I have updated this to be a fix, without try / catch.
The issue was that we could either get the item we want with `.getEntry()`, which by the way is not used on Android, but that can throw an exception if the item has not title.
The right approach here seems to me,  that the getPath and getTitle can be used directly without using .getEntry().
This way it won't throw an error, and we can filter on empty titles, as those would be a blank line in search results, which we probably don't want.
I also checked the above concerns, only 1 search is running at the same time, and it is sticking to 1 thread only, so no threading problem there.

**Comment by rgaudin** [comment]
> @mgautierfr do you confirm that we can call `getPath` and `getTitle` directly on a search result, and get proper values even if the search result is a redirect (looks like this was the intent of original code we had in this repo)?

Yes ; actually what we do in pylibzim is to only retrieve the path and retrieve a regular entry via `getEntryByPath()`.

Two questions:

- If it's returned in suggestions, it might be important so why not returning and displaying path instead of title?
- Can we fix search (this is just suggestion) as well, it seems we're at risk of the same issue

https://github.com/kiwix/apple/blob/main/SwiftUI/Model/SearchOperation/SearchOperation.mm#L77

**Comment by mgautierfr** [comment]
> The right approach here seems to me, that the getPath and getTitle can be used directly without using getEntry().

This is surprising it works and `getTitle` not. `SuggestionItem` is build using data comming from the entry, so internally call `getEntry`.


The trace you provides somehow create `EntryNotFound` exception. So it seems that libzim don't find the entry which is referenced in the index...

Which zim file are we speaking of ? Is there a link somewhere I can download the zim and test ?

**Comment by rgaudin** [comment]
> Which zim file are we speaking of ? Is there a link somewhere I can download the zim and test ?

https://mirror.download.kiwix.org/zim/.hidden/custom_apps/mdwiki_en_all-app_maxi_2023-12.zim

**Comment by BPerlakiH** [comment]
The same happens on the mini version, maybe easier to work with that:
https://mirror.download.kiwix.org/zim/.hidden/custom_apps/mdwiki_en_all-app_mini_2023-12.zim

**Comment by BPerlakiH** [comment]
@mgautierfr The way I observed it is that when the `title` is an empty string, it throws a `EntryNotFound` exception when calling `getEntry()` as in the original code (`main` branch).
On the same note: there's no direct use of `getEntry()` in the Android codebase either.

**Comment by mgautierfr** [comment]
Ok, this appears in this condition:
- Scrapper add a redirect `A/Alpha_GPC` pointing to `A/Alpha-GPC`.
- The pointed article is not added. Here, the error in the log is `Error downloading article Alpha-GPC` 
- Invalid redirect is removed from the archive `Invalid redirection A/Alpha_GPC redirecting to (missing) A/Alpha-GPC` (among others)

The xapian database still have indexed the redirect and so, suggestion search returns the a suggestion to an entry not existing in the zim.

`SuggestionItem::getTitle` return an empty title (because we catch if we cannot find the entry and return a empty string).
`SuggestionIterator::getEntry` raise a `EntryNotFound`.

I would say we have several things to do:
- You should catch the `EntryNotFound` and skip the suggestion in this case.
- Should we (libkiwix) skip this suggestion ourselves and return only valid suggestion ?
- We could remove the suggestion from the titleIndex at creation time (but it may be not so easy to do) but we have already such zim files in the nature, so we must fix reading part anyway.

**Comment by rgaudin** [comment]
@BPerlakiH any progress on adding the title check to search? And displaying the path should the title be empty

**Comment by kelson42** [comment]
@BPerlakiH Any feedback?

**Comment by BPerlakiH** [comment]
I have updated the PR with the same fix for the search as @rgaudin suggested, adding the path as a fallback title (when the title is empty).
@mgautierfr Thank you for the detailed explanation.
I did managed to catch this specific exception: zim::EntryNotFound, which would be more descriptive of the problem that checking the empty title, which (as I understand) is a side effect of the problem.
The difference that I see, and still not fully understand is that if I use `getEntry()` (with the catch) the results displayed are different, than when using `getTitle` + `getPath` directly. The returned results seem to be more relevant than those returned by `getEntry()`. 
For these reasons, I am suggesting to leave this fix as it is for now, and we should investigate what is causing the results to be different at the end.
I did found another (smaller issue with the search results) and will open a new ticket for that.

File: SwiftUI/Model/SearchOperation/SearchOperation.mm [hunk 1]
```diff
@@ -84,6 +84,9 @@ - (void)addIndexSearchResults:(std::vector<zim::Archive>)archives {
         NSUUID *zimFileID = [[NSUUID alloc] initWithUUIDBytes:(unsigned char *)result.getZimId().data];
         NSString *path = [NSString stringWithCString:item.getPath().c_str() encoding:NSUTF8StringEncoding];
         NSString *title = [NSString stringWithCString:item.getTitle().c_str() encoding:NSUTF8StringEncoding];
```
Comment (BPerlakiH) [inline SwiftUI/Model/SearchOperation/SearchOperation.mm:86]: I haven't experience the title being empty here, but we can do a fallback as suggested.

File: SwiftUI/Model/SearchOperation/SearchOperation.mm [hunk 2]
```diff
@@ -108,13 +111,14 @@ - (void)addTitleSearchResults:(std::vector<zim::Archive>)archives count:(int)cou
...
-            
-            zim::Entry entry = result.getEntry();
-            zim::Item item = entry.getItem(entry.isRedirect());
-            NSString *path = [NSString stringWithCString:item.getPath().c_str() encoding:NSUTF8StringEncoding];
-            NSString *title = [NSString stringWithCString:item.getTitle().c_str() encoding:NSUTF8StringEncoding];
-            SearchResult *searchResult = [[SearchResult alloc] initWithZimFileID:zimFileID path:path title:title];
-            if (searchResult != nil) { [self.results addObject:searchResult]; }
+            NSString *path = [NSString stringWithCString:result->getPath().c_str() encoding:NSUTF8StringEncoding];
+            NSString *title = [NSString stringWithCString:result->getTitle().c_str() encoding:NSUTF8StringEncoding];
+            if (title.length > 0) {
```
Comment (rgaudin) [inline SwiftUI/Model/SearchOperation/SearchOperation.mm:116]: But there is no suggestion result for entries without a title… That's where using the path as title is the most important since suggestions are only presented as a Title with no excerpt or anything.

Comment (BPerlakiH) [reply SwiftUI/Model/SearchOperation/SearchOperation.mm:116]: Ok, I see. I did check this scenario as well. Currently if we display such item, the user will face an error trying to opening it. Therefore, I think it is better not to show it:

https://github.com/kiwix/apple/assets/6784320/212b9740-0dfc-4f7e-aa2e-9b07bdbfe674

Comment (BPerlakiH) [reply SwiftUI/Model/SearchOperation/SearchOperation.mm:116]: Screenshot 2024-02-04 at 09 16 21

Comment (rgaudin) [reply SwiftUI/Model/SearchOperation/SearchOperation.mm:116]: OK then but what's the reason for it not loading? This looks like a separate issue that needs a ticket (we don't have to solve it now)

**Review by rgaudin — APPROVED** [review]
LGTM

**Review by benoit74 — COMMENTED** [review]
Nothing more to add

**Review by benoit74 — APPROVED** [review]
LGTM

File: SwiftUI/Model/SearchOperation/SearchOperation.mm (hunk 2 above)
Comment (mgautierfr) [reply SwiftUI/Model/SearchOperation/SearchOperation.mm:116]: > That's where using the path as title is the most important since suggestions are only presented as a Title with no excerpt or anything.
> OK then but what's the reason for it not loading? 

`Suggestion::getTitle` do not throw a exception, it returns an empty title.
So if the title is empty, it is probably because the entry has been removed. Using the path will not help to find the entry.

Comment (kelson42) [reply SwiftUI/Model/SearchOperation/SearchOperation.mm:116]: @rgaudin Good for you there?

**Comment by kelson42** [comment]
I have made a few researches, the problem of "dead" redirects is old and known, see https://github.com/openzim/libzim/issues/240.
